INSERT OR IGNORE INTO "Addition" VALUES (1,"A crayon company recently changed its labels. It currently has 121 crayons with the old label and 585 crayons with the new label. How many crayons does the company have in stock?","t","0","0","0","0","706","false");
INSERT OR IGNORE INTO "Addition" VALUES (2,"Pizzeria Pepperoni sold 46 pepperoni pizzas, 734 veggie pizzas, and 7 cheese pizzas. How many pizzas did they sell in all?","t","0","0","0","0","787","false");
INSERT OR IGNORE INTO "Addition" VALUES (3,"Billy donated money to various programs last year. First, he donated $441 to the community center and $6 to save endangered animals. Then he donated $69 to a medical foundation. How much money did Billy donate in all?","t","0","0","0","0","516","false");
INSERT OR IGNORE INTO "Addition" VALUES (4,Questuin title,"i","jpg","2","3","4","1","false");
INSERT OR IGNORE INTO "Addition" VALUES (5,Questuin title,"i","jpg","2","3","4","1","false");
INSERT OR IGNORE INTO "Addition" VALUES (6,Questuin title,"i","jpg","2","3","4","1","false");
INSERT OR IGNORE INTO "Addition" VALUES (7,Questuin title,"m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Addition" VALUES (8,Questuin title,"m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Addition" VALUES (9,Questuin title,"m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Addition" VALUES (10,Questuin title,"m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Addition" VALUES (11,Questuin title,"m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Subtraction" VALUES (1,"There were a total of 664 tadpoles in a pond. One afternoon, Ariel caught 29 tadpoles from the pond and took them home. How many tadpoles were left in the pond?","t","0","0","0","0","635","false");
INSERT OR IGNORE INTO "Subtraction" VALUES (2,"A large company is hosting a conference. So far, a total of 845 people have signed up, including 43 from the United States. How many people from other countries have signed up?","t","0","0","0","0","802","false");
INSERT OR IGNORE INTO "Subtraction" VALUES (3,"A banana farm received a total of 581 millimeters of rain in March and April. If 18 millimeters of rain fell on the farm in March, how many millimeters of rain fell on the farm in April?","t","0","0","0","0","563","false");
INSERT OR IGNORE INTO "Subtraction" VALUES (4,"image question","i","jpg","2","3","4","1","false");
INSERT OR IGNORE INTO "Subtraction" VALUES (5,"image question","i","jpg","2","3","4","1","false");
INSERT OR IGNORE INTO "Subtraction" VALUES (6,Questuin title,"m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Subtraction" VALUES (7,Questuin title,"m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Subtraction" VALUES (8,Questuin title,"m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Subtraction" VALUES (9,Questuin title,"m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Subtraction" VALUES (10,Questuin title,"m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Multiplication" VALUES (1,"A baker made 5 cakes. He cut each cake into 3 slices. How many slices of cake did the baker end up with?","m","21","15","8","12","15","false");
INSERT OR IGNORE INTO "Multiplication" VALUES (2,"Brooke bought 6 sweaters at the mall. Each sweater cost $11. How much money did Brooke spend?","t","0","0","0","0","66","false");
INSERT OR IGNORE INTO "Multiplication" VALUES (3,"A clothing company ordered sweatshirts in 2 different colors. They ordered 411 of each color. How many sweatshirts did the clothing company order in all?","t","0","0","0","0","822","false");
INSERT OR IGNORE INTO "Multiplication" VALUES (4,"image question","i","jpg","2","3","4","1","false");
INSERT OR IGNORE INTO "Multiplication" VALUES (5,"image question","i","jpg","2","3","4","1","false");
INSERT OR IGNORE INTO "Multiplication" VALUES (6,Questuin title,"i","jpg","2","3","4","1","false");
INSERT OR IGNORE INTO "Multiplication" VALUES (7,Questuin title,"m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Multiplication" VALUES (8,Questuin title,"m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Multiplication" VALUES (9,Questuin title,"m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Multiplication" VALUES (10,Questuin title,"m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Multiplication" VALUES (11,Questuin title,"m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Division" VALUES (1,"A math teacher has $824 to buy new calculators. If each calculator costs $8, how many calculators can the teacher buy?","t","0","0","0","0","103","false");
INSERT OR IGNORE INTO "Division" VALUES (2,"A summer camp has 972 campers. If 9 campers can sleep in each cabin, how many cabins will the campers need?","t","1","2","3","4","108","false");
INSERT OR IGNORE INTO "Division" VALUES (3,"There are 3,604 students at a concert. If there are 6 seats in each row, how many rows will the students need?","t","0","0","0","0","601","false");
INSERT OR IGNORE INTO "Division" VALUES (4,"Is 94 divisible by 2? yes or no","t","0","0","0","0","yes","false");
INSERT OR IGNORE INTO "Division" VALUES (5,"image question","i","jpg","2","3","4","1","false");
INSERT OR IGNORE INTO "Division" VALUES (6,"image question","i","jpg","2","3","4","1","false");
INSERT OR IGNORE INTO "Division" VALUES (7,"i","m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Division" VALUES (8,Questuin title,"m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Division" VALUES (9,Questuin title,"m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Division" VALUES (10,Questuin title,"m","1","2","3","4","1","false");
INSERT OR IGNORE INTO "Division" VALUES (11,Questuin title,"m","1","2","3","4","1","false");